### ISSUE TITLE
InkLibraryAsset is overwritten with an empty one when opening a project for the first time

### ISSUE THREAD

**Issue by gboulard** [inkle/ink-unity-integration#56] opened 2018-03-23 10:19 UTC
When we retrieve the unity project on a new machine (via control source) , the InkLibrary.asset is overwritten with an empty one.

this is due to the fact the code check the existence of a key in EditorPrefs (see FindOrCreateSingletonScriptableObjectOfType)

is there any particular reason to use an EditorPrefs Key ?

**Comment by tomkail** [comment] 2018-03-27 16:05
We use the editorprefs key because finding the InkLibrary asset via
AssetDatabase.FindAssets is quite expensive, and storing the asset
reference this way saves calling it each time unity recompiles.
What's really happening here, I think, is that it fails to find the
editorpref (as expected for a new machine), and then tries to find the
asset via AssetDatabase.FindAssets but fails because it's not yet imported
it. Since it thinks that there's no library, it creates a new one.
The kicker is that the system should resolve this on recompile when it
finds two files by deleting the newest one - but since you must have the
asset in the default path, creating a new asset overwrites the old one.
We can fix this specific case by attempting to import at the default path
but that's not really a robust fix.
The only fix I can think of is to search the file directory for the file
rather than the AssetDatabase, but that's really horrible since there's no
way to get the asset type without actually reading the file. So I'm stumped!
Anyone in the community have a fix for this in mind?

**Comment by tomkail** [comment] 2018-05-04 06:12
We use a playerprefs key based on the project name to get around that one. 
The problem, I think, with the second point is that the scriptable object hasn’t been imported at the time the bug occurs.

The file you suggest sounds good to me, although it’s a shame to need an extra file! For extra credit, I’d be very interested in ways of saving and loading a scriptable object into the project setting folder that contains the settings for input etc.

**Comment by KumoKairo** [comment] 2018-05-04 08:29
> it’s a shame to need an extra file!

Technically EditorPrefs does that as well, it's just a hidden file

> I’d be very interested in ways of saving and loading a scriptable object into the project setting folder that contains the settings for input etc.

I'd look into a few ways of addressing it, will write back by the end of the next week (May 13) with the results

**Comment by KumoKairo** [comment] 2018-05-07 10:47
Okay, I confirm that `ScriptableObject`'s `OnEnable / OnDisable` method is working okay, without the need of accessing any separate files or `EditorPrefs`. The technique just uses those Unity Messages on `ScriptableObjects` to hard-set the static _Instance for the Library. Methods are called in needed order, without any "missed" calls like it happens in some cases, so there are no calls to those `FastFindAndEnforceSingletonScriptableObjectOfType` methods.

I have also noted the same `EditorPrefs` technique with the `InkSettings` file too, so it can also be replaced with a simpler one.

I would also suggest storing `Last Compile Time` directly inside of the `InkLibrary` file so everything remains project-based instead of machine-based.

One question remains though, about the UX of the new Ink Library file creation. If I delete one, the code of InkLibrary-related stuff doesn't try to create a new one until I reopen the project. Is there a reason behind it? Shoudln't it be creating a new default file once the old one is deleted?

**Comment by KumoKairo** [comment] 2018-05-08 15:04
> Hmm the ink library is supposed to create itself if it doesn’t exist whenever it’s needed - is that not working?

The code that's in the Compiler's Update method only checks if a Library exists or tries to find it, without creating.
It only tries to create one at Unity startup. 
So I don't think it's the definition of "not working",  it's looks like expected behavior

**Comment by tomkail** [comment] 2018-05-09 09:51
I've got this in our project and I'm going to let it settle for a bit. I'm still wary of if it'll fix the original bug (although it's clearly better code if it works) because of how Unity sometimes staggers importing assets but it looks hopeful! Thanks for your work!

**Comment by KumoKairo** [comment] 2018-05-17 16:15
I've found a small issue with the static link check (should check for `_link != this`), other than that it's working OK in our project. How about spreading the "store everything in SO" tactics further, to completely eliminate EditorPrefs?

**Comment by KumoKairo** [comment] 2018-05-17 16:31
Can you specify which meta-info is required to be local?

**Comment by tomkail** [comment] 2018-05-17 16:37
There’s a class called inkmetainfo or something - it stores relationships
between files.

**Comment by tomkail** [comment] 2018-05-18 10:40
I've pushed your changes (and a few of my own). I'm going to close this issue since it's been fixed, but if you manage to find a nicer way to store InkMetaFile data than playerprefs I'd love to get it in!

**Closed by tomkail** 2018-05-18 10:40 UTC
